<?php

namespace App\Enums;

enum SystemEventType: string
{
    case APP_UPDATE = 'APP_UPDATE';
    case MEMBER_BANNED = 'MEMBER_BANNED';
    case MEMBER_ACTIVE = 'MEMBER_ACTIVE';

    case TRACKING_DISABLED = 'TRACKING_DISABLED';
    case TRACKING_ENABLED = 'TRACKING_ENABLED';
    case GS_UPDATE = 'GS_UPDATE';
    case PROJECT_ASSIGNED = 'PROJECT_ASSIGNED';
    case PROJECT_UNASSIGNED = 'PROJECT_UNASSIGNED';
    case TASK_ASSIGNED = 'TASK_ASSIGNED';
    case TASK_UNASSIGNED = 'TASK_UNASSIGNED';
    case SYSTEM_ALERT = 'SYSTEM_ALERT';
}
